Fix infinite loop
JohannesKlauss/react-hotkeys-hook pull request #945
Opened 2023-02-10 23:47 UTC by TravisL12

https://github.com/JohannesKlauss/react-hotkeys-hook/issues/944

This fixes an infinite loop that is caused by an array dependency in a `useEffect`. I simply serialize the array dependency in question only because using a ref or memoizing the `keys` prop was causing a test failure in `tests/useHotkeys.test.tsx L#274`.

2023-02-18 10:56 UTC, JohannesKlauss requested changes

2023-02-18 10:56 UTC, JohannesKlauss commented on src/useHotkeys.ts
> +  }, [JSON.stringify(keys), memoisedOptions, enabledScopes])
Hmh... I don't really want to use JSON.stringify here. It's an expensive operation and you shouldn't hack the dependency array that way. A better approach in my opinion would be to make sure we are always dealing with a string:

```ts
const _keys = keys instanceof Array ? keys.join(_options?.splitKey) : keys
```

Then we can reference the `_keys` everywhere we use `keys` and also the check in `parseKeysHookInput` could be removed.

2023-02-23 18:58 UTC, TravisL12 commented
Thanks @JohannesKlauss I'm trying to prioritize some time to make these changes.

2023-03-07 17:20 UTC, TravisL12 commented
@JohannesKlauss sorry for the delay but I've updated the PR per your comment. Let me know if that works out alright!

2023-03-13 10:23 UTC, merged