[feature]: ignoreEventCondition option
JohannesKlauss/react-hotkeys-hook pull request #980
Opened 2023-03-14 08:59 UTC by alpinagyok

Hey!

### Changes

- added `ignoreEventCondition` option

### Why

We need a bit finer control of when to ignore events. As an example, checking `event.target.closest()` by role/css

Wdyt? 😄

2023-03-19 08:42 UTC, JohannesKlauss commented
Please add some tests for that feature and add its API to the API documentation. Also I am not too happy about the name of the option. Maybe something like `ignoreEventWhen` is a more precise naming?

2023-03-19 12:39 UTC, alpinagyok commented
Agree with the name 👍, thanks for the comment. Will add tests and docs in a moment

2023-03-19 14:03 UTC, alpinagyok commented
@JohannesKlauss, done 👌

2023-03-24 08:19 UTC, JohannesKlauss requested changes

2023-03-24 08:19 UTC, JohannesKlauss commented on documentation/docs/api/use-hotkeys.mdx
> +
This text is now doubled

2023-03-24 08:19 UTC, JohannesKlauss commented on tests/useHotkeys.test.tsx
> +  expect(callback).toHaveBeenCalledTimes(1)
I don't quite understand this. The behavior I expected would be that the callback never gets called. Why would it get called the first time and what is the button click doing?

2023-04-11 17:25 UTC, alpinagyok commented on documentation/docs/api/use-hotkeys.mdx
> +
fixed 👍

2023-04-14 14:12 UTC, JohannesKlauss approved these changes

2023-04-14 14:12 UTC, JohannesKlauss commented
Thank you for your work!

2023-04-14 14:12 UTC, merged

2023-04-25 16:28 UTC, Isti115 commented
Sorry to bump this already merged PR, but just out of curiosity I'd like to ask what the difference between `filter` and `ignoreEventWhen` is apart from the predicate being negated? Having both of these options only for the sake of one being affected by `filterPreventDefault` and the other not seems to be a bit redundant to me at first, but there might be something that I`m overlooking.

Also, if `ignoreEventWhen` is necessary, it should probably also be documented in the _Options_ table of the top level README.

2023-04-28 16:18 UTC, alpinagyok commented
@Isti115, I didn't know those existed 😄. but now that I look at it, there's no mention of `filter` in the code. maybe it's a leftover documentation? probably a question for the maintainer

2023-04-28 18:32 UTC, Isti115 commented
@alpinagyok Wow, sorry for not checking thoroughly enough, you're completely right, it seems to have been removed at some point during the move to version 4 as far as I can tell from the commit history. I'll submit a PR to remove it from the documentation as well.